var Monstres = [
   ["Abishaii Bleu", 19, true],
   ["Abishaii Noir", 10, true],
   ["Abishaii Rouge", 23, true],
   ["Abishaii Vert", 15, true],
   ["Ame en peine", 8, true],
   ["Amibe géante", 9, false],
   ["Anaconda des Catacombes", 8, true],
   ["Ankheg", 10, true],
   ["Anoploure Purpurin", 36, true],
   ["Araignée Géante", 2, true],
   ["Aragnarok du Chaos", 16, true],
   ["Ashashin", 35, true],
   ["Balrog", 50, true],
   ["Banshee", 16, true],
   ["Barghest", 36, true],
   ["Basilik", 11, true],
   ["Behemoth", 34, true],
   ["Behir", 14, true],
   ["Beholder", 50, true],
   ["Boggart", 3, true],
   ["Bondin", 9, true],
   ["Bouj'Dla", 19, true],
   ["Bouj'Dla Placide", 37, true],
   ["Bulette", 19, true],
   ["Caillouteux", 1, true],
   ["Capitan", 35, true],
   ["Carnosaure", 25, true],
   ["Champi-Glouton", 3, true],
   ["Chauve-Souris Géante", 4, true],
   ["Cheval à Dent de Sabre", 23, true],
   ["Chimère", 20, true],
   ["Chonchon", 24, true],
   ["Coccicruelle", 22, true],
   ["Cockatrice", 5, true],
   ["Crasc", 0, true],
   ["Crasc Maexus", 25, true],
   ["Crasc Medius", 25, true],
   ["Croquemitaine", 6, true],
   ["Cube gâlatineux", 32, false],
   ["Daémonite", 27, true],
   ["Diablotin", 5, true],
   ["Dindon", 1, true],
   ["Djinn", 29, false],
   ["Ectoplasme", 18, false],
   ["Effrit", 27, true],
   ["Elémentaire d'Air", 23, false],
   ["Elémentaire d'Eau", 17, false],
   ["Elémentaire de Feu", 21, false],
   ["Elémentaire de Terre", 21, false],
   ["Elémentaire du Chaos", 26, false],
   ["Erinyes", 7, true],
   ["Esprit Follet", 16, false],
   ["Essaim Cratérien", 30, true],
   ["Essaim Sanguinaire", 25, true],
   ["Ettin", 8, true],
   ["Fantéme", 24, false],
   ["Feu Follet", 20, false],
   ["Flagelleur Mental", 33, true],
   ["Foudroyeur", 38, true],
   ["Fumeux", 22, true],
   ["Fungus Géant", 9, true],
   ["Fungus Violet", 4, true],
   ["Furgolin", 10, true],
   ["Gargouille", 3, true],
   ["Géant de Pierre", 13, true],
   ["Géant des Gouffres", 22, true],
   ["Géant des Tempétes", 0, true],
   ["Geck'oo Majestueux", 40, true],
   ["Geck'oo", 15, true],
   ["Glouton", 20, true],
   ["Gnoll", 5, true],
   ["Gnu Sauvage", 1, true],
   ["Goblin", 4, true],
   ["Goblours", 4, true],
   ["Golem d'Argile", 14, false],
   ["Golem de Chair", 9, false],
   ["Golem de Fer", 24, false],
   ["Golem de Pierre", 19, true],
   ["Gorgone", 11, true],
   ["Goule", 4, true],
   ["Gowap", 1, true],
   ["Gremlins", 3, true],
   ["Gritche", 39, true],
   ["Grouilleux", 4, true],
   ["Grylle", 31, true],
   ["Harpie", 4, true],
   ["Hellrot", 18, true],
   ["Homme-Lézard", 4, true],
   ["Hurleur", 8, true],
   ["Hydre", 50, true],
   ["Incube", 13, true],
   ["Kobold", 2, true],
   ["Labeilleux", 26, true],
   ["Lapin Blanc", 0, true],
   ["Lézard Géant", 5, true],
   ["Liche", 50, true],
   ["Limace Géante", 10, true],
   ["Loup-Garou", 8, true],
   ["Lutin", 4, true],
   ["Mante Fulcreuse", 30, true],
   ["Manticore", 9, true],
   ["Marilith", 33, true],
   ["Méduse", 6, true],
   ["Mégacéphale", 38, true],
   ["Mille-pattes Géant", 14, true],
   ["Mimique", 6, false],
   ["Minotaure", 7, true],
   ["Mohrg", 35, true],
   ["Molosse Satanique", 8, true],
   ["Momie", 4, true],
   ["Monstre Rouilleur", 3, true],
   ["Mouch'oo", 14, true],
   ["Mouch'oo Majestueux", 33, true],
   ["Naga", 10, true],
   ["Nécrochore", 37, true],
   ["Nécromant", 39, true],
   ["Nécrophage", 8, true],
   ["Nuage d'Insectes", 7, true],
   ["Nuée de Vermine", 13, true],
   ["Ogre", 7, true],
   ["Ombre", 2, false],
   ["Ombre de Roches", 12, true],
   ["Orque", 3, true],
   ["Ours-Garou", 18, true],
   ["Palefroi Infernal", 29, true],
   ["Phoenix1", 32, true],
   ["Phoenix2", 34, true],
   ["Phoenix3", 36, true],
   ["Plante Carnivore", 4, true],
   ["Pseudo-Dragon", 5, true],
   ["Rat Géant", 2, true],
   ["Rat-Garou", 3, true],
   ["Rocketeux", 5, true],
   ["Sagouin", 3, true],
   ["Scarabée Géant", 5, true],
   ["Scorpion Géant", 10, true],
   ["Shai", 28, true],
   ["Sirène", 0, true],
   ["Slaad", 5, true],
   ["Sorcière", 17, true],
   ["Spectre", 14, false],
   ["Sphinx", 30, true],
   ["Squelette", 1, true],
   ["Strige",21, true],
   ["Succube", 13, true],
   ["Tertre Errant", 20, true],
   ["Thri-Kreen", 10, true],
   ["Tigre-Garou", 12, true],
   ["Titan", 26, true],
   ["Trancheur", 35, true],
   ["T-Rex", 0, true],
   ["Troll Noir", 0, true],
   ["Tubercule Tueur", 14, true],
   ["Tutoki", 4, true],
   ["Vampire", 29, true],
   ["Ver Carnivore Géant", 12, true],
   ["Veskan du Chaos", 14, true],
   ["Vouivre", 33, true],
   ["Worg",5, true],
   ["Xorn", 14, true],
   ["Yéti", 7, true],
   ["Yuan-Ti", 15, true],
   ["Zombie", 2, true],
   ["", 0, false]
];

var Potions = [
   ["Potion mélangée"],
   ["Dover Powa"],
   ["Elixir de Bonne Bouffe"],
   ["Elixir de Corruption"],
   ["Elixir de Fertilité"],
   ["Elixir de Feu"],
   ["Elixir de Longue-Vue"],
   ["Essence de KouleMann"],
   ["Extrait de DjhinTonik"],
   ["Extrait du Glacier"],
   ["Grippe en Conserve"],
   ["Jus de Chronomètre"],
   ["Métomol"],
   ["Pneumonie en Conserve"],
   ["Potion de Guérison"],
   ["Potion de painthure"],
   ["PufPuff"],
   ["Rhume en Conserve"],
   ["Sang de Toh Réroh"],
   ["Sinne Khole"],
   ["Toxine Violente"],
   ["VoiPuRin"],
   ["Zet Crakdedand"],
   
   [""]
];
